import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";
export const metadata: Metadata = {
  title: {
    template: '%s | TODOLIST',
    default: 'TODOLIST', // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className={`antialiased `}>
        {" "}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
